name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: project builds
      id: project-builds
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: project builds
        setup-command: ''
        command: make
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PROJECT-BUILDS_RESULTS: "${{steps.project-builds.outputs.result}}"
      with:
        runners: project-builds
